---
- name: Install OpenJDK
  apt: name=openjdk-7-jre-headless state=present

- name: Fetch storm package
  get_url: dest=/root/apache-storm-{{storm_version}}.tar.gz url="{{apache_mirror}}/storm/apache-storm-{{storm_version}}/apache-storm-{{storm_version}}.tar.gz"
