---
- name: Install OpenJDK
  apt: name=openjdk-7-jre-headless state=present

- name: setup group
  group: name={{storm_group}} system=yes
- name: Setup user
  user: name={{storm_user}} system=yes group={{storm_group}}

- name: Create Storm root directory
  file: path={{storm_root_dir}} state=directory owner={{storm_user}} group={{storm_group}} mode=755

- name: Fetch storm package
  get_url: dest=/root url="{{apache_mirror}}/incubator/storm/apache-storm-{{storm_version}}/apache-storm-{{storm_version}}.tar.gz"

- name: Uncompress the storm tar
  unarchive: copy=no creates={{storm_root_dir}}/apache-storm-{{storm_version}} dest={{storm_root_dir}} src=/root/apache-storm-{{storm_version}}.tar.gz

- name: Link current version
  file: path={{storm_root_dir}}/current state=link src={{storm_root_dir}}/apache-storm-{{storm_version}}

- name: Configure storm.yaml
  template: dest="{{storm_root_dir}}/apache-storm-{{storm_version}}/conf/storm.yaml" owner={{storm_user}} group={{storm_group}} mode=640 src=storm.yaml.j2
  notify:
    - Restart Nimbus
    - Restart Supervisor
    - Restart UI

- include: nimbus.yml tags=storm_nimbus 
  when: storm_nimbus_enabled

- include: supervisor.yml tags=storm_supervisor
  when: storm_supervisor_enabled
